### ISSUE TITLE
Wenlei Dai 15.2.19 tiralabra3 code review week5

### ISSUE THREAD

**Issue by rescawen** [Zentryn/ChessAI#1]
Time at when first cloned project 15.2, 10AM. No changes made to project until I submitted this code review.

There were problems in the installation. After running npm install, most things went smoothly until it tried to run something related to python. I tried it on 2 different computers and with python 3.6. I thought the version of python is the problem and installed the latest version of python 3.7.2 and it still gave the same error.  The photo below is the result of npm install. All other photos have the command in them except this one.

<img width="960" alt="2019-02-15" src="https://user-images.githubusercontent.com/22350348/52866321-12d68b00-3147-11e9-87b1-8ae2a502397e.png">

Installing build tools for visual studio 2017 to try to fix the problems of installation. It is a giant 4.5gb file and the installation had a lot of options so I went with the default ones. After some googling I tried to do npm i -g node-gyp configure build, it did successfully generate a build. However this did not solve any installation problems. 

<img width="960" alt="2019-02-15 1" src="https://user-images.githubusercontent.com/22350348/52866278-03574200-3147-11e9-9620-9c92068c06cd.png">

Running the tests also yielded in errors as expected because of all the problems above.

<img width="960" alt="2019-02-15 2" src="https://user-images.githubusercontent.com/22350348/52866318-0fdb9a80-3147-11e9-84a5-a9192f0a6861.png">

Due to the problematic installation after starting up the application the page is totally blank with background. I have worked with electron before and it might have been wise to create a compiled version of the app so I could have installed it locally to my computer. This might eliminate problems related to installation. 

<img width="960" alt="2019-02-15 3" src="https://user-images.githubusercontent.com/22350348/52866550-96907780-3147-11e9-9d8e-1cbadf4105de.png">

I browsed around lichess.org and checked out some replays. I might be nitpicking but all I can say is maybe use folders inside the Engine folder to further split things up a little bit more clearer. If I understood correctly after reading the implementation document the magic mostly happens on [calculate function](https://github.com/Zentryn/ChessAI/blob/master/src/Engine/Engine.cpp#L95) and [search function](https://github.com/Zentryn/ChessAI/blob/master/src/Engine/Engine.cpp#L164).

If everything else except magicmoves.cpp/hpp is written by yourself then it is an incredible undertaking that you pursued for this course. Nothing else to say except well done. I have only used c++ for one algorithm course and don’t remember much. It seems like c++ creates a code structure not so easy to read. So to summarize I don't have enough skills to analyse this code on a deep level, but it was pleasure to take a look at a great project!

**Comment by Zentryn** [comment]
The problem with python seems to be that you didn't add it to your PATH environment variable. I've also had problems with python 3.x in the past while installing NodeJS packages, but python 2.x has seemed to work well. These should've been included in the docs, but have now been added.
